### ISSUE TITLE
[Feature Request] Add support for suggestions url

### ISSUE THREAD

**Issue by FatOrangutan** [evilpie/add-custom-search-engine#1]
Firefox [supports](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) `application/x-suggestions+json` for search suggestions.

**Comment by evilpie** [comment]
I like the idea. However I think you basically already need to know how opensearch works to understand this. Maybe I could add something that is more of an advanced mode for basically creating opensearch descriptions.
