### ISSUE TITLE
need without '+' every space in %s string. 

### ISSUE THREAD

**Issue by Kay32** [evilpie/add-custom-search-engine#10]
I want it to translation like google translation. 

please insert option without auto insert '+'

**Comment by evilpie** [comment]
Can you please rephrase your question? I have a hard time understanding you.

So I think what you are saying is that when you search for something, a space character is encoded as `+`? This is actually done by the browser and is "normal" URL encoding.

**Comment by Kay32** [comment]
I added like below 'Search URL'
https://papago.naver.com/?sk=auto&tk=ko&st=%s

I expect below URL when I searching. 
https://papago.naver.com/?sk=auto&tk=ko&st=Because%20both%20of%20them%20refer%20to%20the%20same%20closure%2C%20they%20both%20increment%20and%20return%20the%20same%20running%20total.

But it actually does this.
https://papago.naver.com/?sk=auto&tk=ko&st=Because%2Bboth%2Bof%2Bthem%2Brefer%2Bto%2Bthe%2Bsame%2Bclosure%2C%2Bthey%2Bboth%2Bincrement%2Band%2Breturn%2Bthe%2Bsame%2Brunning%2Btotal.

**Comment by evilpie** [comment]
I am afraid there is nothing I can do. The browser decides how to encode this information and I am not aware of any parameter we could use to change it.

**Comment by dimaqq** [comment]
My understanding of the OP is that `custom-search-engine` changes spaces to plus signs, i.e. changes `%20` to `%2B` which changes text semantics in naver translate tool.
Below are the screenshots to highlight the difference:

<img width="661" alt="Screenshot 2019-05-09 at 11 30 27" src="https://user-images.githubusercontent.com/662249/57423201-f3cf2d00-724d-11e9-819e-fed688c05367.png">
<img width="603" alt="Screenshot 2019-05-09 at 11 30 41" src="https://user-images.githubusercontent.com/662249/57423204-f7fb4a80-724d-11e9-84a2-9ecb9d248306.png">

**Comment by evilpie** [comment]
My extension doesn't change `%20` to `%2B`. Firefox replaces `{searchTerms}` with the entered search query and it also decides how to encode spaces.

**Comment by Korb** [comment]
For the same reason, searching the **AppAgg** site is not possible. Instead of link

`https://appagg.com/search/cyberpunk%202077:steam-games/?hl=en`

link

`https://appagg.com/search/cyberpunk+2077:steam-games/?hl=en`

is sent.
