### ISSUE TITLE
features suggestions

### ISSUE THREAD

**Issue by Mike-Reddick** [evilpie/add-custom-search-engine#14]
Please add features to fetch other resolutions of favicon as HD icons, and add google as default url to auto complete, I ever use google to auto complete and I ever need copy and paste this. Another suggestion, an feature to allow upload to an ftp server.

thanks

**Comment by evilpie** [comment]
Thanks for opening this issue. I am afraid I don't think any of your suggestions are immediately actionable, but feel free to explain your ideas in a bit more detail if I misunderstood something.

> Please add features to fetch other resolutions of favicon as HD icons

Right now we only autofill the URL ending with `favicon.ico` for convenience. We can't know the existence of actual icons with higher resolution without loading the Search URL and parsing the HTML source code. Loading this URL would require adding additional permissions that seem IMO out of place for this extension.

>and add google as default url to auto complete, I ever use google to auto complete and I ever need copy and paste this

This tool is for adding custom search engines, I don't see how this would be useful. Firefox already ships with Google preinstalled. I am also categorically against favoring Google vs other search engines.

>Another suggestion, an feature to allow upload to an ftp server.

Sadly this is not technically possible: WebExtensions can't connect to FTP servers. (Without native messaging, which I definitely don't plan on adding)

**Comment by Mike-Reddick** [comment]
> We can't know the existence of actual icons with higher resolution without loading the Search URL and parsing the HTML source code. Loading this URL would require adding additional permissions that seem IMO out of place for this extension

And if you add an new button to process HTML source code and show other icons resolutions, so, this new permission can be "by demand", only if user use this new button "Fetch Other Icons Resolutions" you can even show an warning in the first time.

> This tool is for adding custom search engines, I don't see how this would be useful. Firefox already ships with Google preinstalled. I am also categorically against favoring Google vs other search engines.

I said about the setting "Show advanced options => Suggest URL". Each site have an specific "Suggest URL" many times is very hard to find this url, so, ever when I add an new search engine, for instance for Bing, Wikipedia, I ever use "https://www.google.com/complete/search?client=firefox&q={searchTerms}" as "Suggest URL". So, I use Bing with google suggestion, because this suggestions is universal and very good. I'm just asking to put this url as default or add an button to use it easy.

**Comment by Mike-Reddick** [comment]
@evilpie ?

**Comment by Mike-Reddick** [comment]
Seem I lost my time trying help this dead project!

**Comment by evilpie** [comment]
Thank you for your interest. Your idea for requesting icons is actually quite good, but I feel like it's a bit too complicated. I want to keep this extension quite lean.

I now understand your idea for suggestion URLs, but I still don't think it makes much sense for most users.
