### ISSUE TITLE
focus on search box

### ISSUE THREAD

**Issue by Ameseattle** [evilpie/add-custom-search-engine#15]
When I go to create a new custom search, I paste the URL.  When I go to the firefox search box & enter a query, it opens the URL.  I want it to act as if I actually entered the query in the search box on the URL page and open the results of the search.  I am a novice; I am guessing I have to add something else, maybe in the advanced section?  Thanks for any help!

**Comment by evilpie** [comment]
What exactly are you pasting into "Search URL" ? Don't forget you have to add *%s*, which will be replaced by the actual search query.

**Comment by evilpie** [comment]
@Ameseattle Did that resolve your issue?
