### ISSUE TITLE
Post based search engine

### ISSUE THREAD

**Issue by khabib227** [evilpie/add-custom-search-engine#16]
Some services haven't an "Search URL" , when you search the URL don't change, is Post based engines, can you add a feature to use this kind of search engine?

**Comment by evilpie** [comment]
Yes. Enable the advanced options.

**Comment by evilpie** [comment]
@khabib227 Did that help?

**Comment by shvchk** [comment]
A bit unexpected that it appears *above* advanced options checkbox. Didn't notice at first.
