### ISSUE TITLE
[Feature Request] Space Replacement Options

### ISSUE THREAD

**Issue by EberHure** [evilpie/add-custom-search-engine#17]
Some websites use different things to replace spaces like "%2B" or "_" instead of "+". It'd be cool if when making a custom search engine, you could specify what takes the place of spaces you type.

**Comment by evilpie** [comment]
The encoding of the actual search parameters is done by Firefox. This extensions just tells Firefox the URL looks like `https://example.org/search?query={searchTerms}`, but the replacement depends on Firefox. There is potentially the "Input Encoding" option, but as far as I know this won't allow this either.

Sorry. I can't help you.
