### ISSUE TITLE
Data URI icon missing from one-off search bar on Firefox homepage

### ISSUE THREAD

**Issue by Quisquose** [evilpie/add-custom-search-engine#19]
I added a custom search engine that has a data URI icon (i.e. embedded base64, _not_ a url link). 

The icon displays fine in both the dedicated search bar and in the 'one-off' search bar at the bottom of the browser's navigation / address URL-bar droplist. However, the icon is missing from the one-off search bar on Firefox's home page (about:home). 

See screenshot below:

![Clipboard01](https://user-images.githubusercontent.com/7541455/83632917-fe1a4280-a597-11ea-84fc-04cf68f21d06.png)

This does not happen in custom search engines where the icon is linked using a url. In those instances the icons display correctly in all places. Icons also display correctly when adding non-custom search engines using the conventional built-in method. I'm therefore assuming that the missing icon is an _Add custom search engine_ issue, rather than a Firefox issue. It may possibly be due to the fact that the icon being used is a vector image (SVG) instead of raster image (PNG).

I have repeated this problem by creating new search engines with different SVG icons using base64, and each time the icon is not displayed on the Firefox home page one-off search (while displaying correctly everywhere else).

Here is a link to an example of the icon data of a missing icon (in case it's of use):  https://pastebin.com/EhiQQXRK

**Comment by evilpie** [comment]
That must be a Firefox bug considering the data: URL works correctly in other places. The correct place for reporting that bug to Mozilla would be: https://bugzilla.mozilla.org/home
