### ISSUE TITLE
connection to file.io

### ISSUE THREAD

**Issue by atomGit** [evilpie/add-custom-search-engine#2]
apparently this add-on uses file.io to create the plugin even when a description is not added, though this is not stated in the AMO description

just curious why it needs to use an external resource at all

thanks

**Comment by atomGit** [comment]
never mind - i believe i found the answer to my question in the [https://github.com/soufianesakhi/firefox-search-engines-helper/blob/master/README.md](Search Engines Helper) GitHub page

**Comment by atomGit** [comment]
from the privacy policy on AMO...

> Due to a technical limitation in Firefox your search engine description is temporarily uploaded to file.io.

this leads one to believe that a connection to file.io is not made _unless_ one provides a description

**Comment by evilpie** [comment]
Oh, I see. This comes from "[OpenSearch description formation](https://developer.mozilla.org/en-US/docs/Web/OpenSearch)". I might think of some better term.

**Comment by atomGit** [comment]
oh, also wanted to ask why the connection to file.io is not in the add-on permissions? i'm just curious and this question is not really specific to your extension - i'm just wondering if you might know why this may be

even when i use the Project Insight extension, it doesn't list the file.io URL

**Comment by evilpie** [comment]
Thanks, I think that is good description. 

> oh, also wanted to ask why the connection to file.io is not in the add-on permissions?

file.io uses [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), so any website (including a webextension page) could upload data to it.
