### ISSUE TITLE
Use Firefox Send instead of file.io

### ISSUE THREAD

**Issue by yoasif** [evilpie/add-custom-search-engine#21]
Seen some comments that people don't trust your usage of file.io: https://www.reddit.com/r/firefox/comments/hbf032/why_is_it_so_hard_to_add_a_custom_search_url/fvb13yy/

I'm curious to know if you can use Firefox Send instead for the ephemeral file sharing required to make this add-on work. 

Just a thought!

**Comment by evilpie** [comment]
It's not possible. Firefox Send doesn't provide a plain text endpoint that we need to provide the OpenSearch XML.
