### ISSUE TITLE
Add examples for using the url suggestion

### ISSUE THREAD

**Issue by dominikaaaa** [evilpie/add-custom-search-engine#22]
Hi, I tried this `https://www.google.com/complete/search?q={searchterm}&client=partner&partnerid=000000000000000000000:xxxxxxxxxxx&ds=cse` and also `http://www.google.com/complete/search?q={searchTerms}&ds=cse&output=firefox` and neither worked. Firefox 77.0.1, Linux 5.6.13-arch1-1

Neither of these seem to work, adding examples for it would be helpful

**Comment by evilpie** [comment]
Good point. I should add some placeholder text for this as well.
I tried `https://www.google.com/complete/search?client=firefox&q={searchTerms}` and it's working for me in the search bar.

**Comment by dominikaaaa** [comment]
Thank you, that works.

**Comment by evilpie** [comment]
Fixed by 1ab49084838e6704a35eaf1654fc8b5aad8243c4
