### ISSUE TITLE
Cyrillic is not supported.

### ISSUE THREAD

**Issue by Acid-Crash** [evilpie/add-custom-search-engine#23]
Add custom search engine v3.0 Firefox 78.0.2.
When trying to add new search engine with name that contains Cyrillic characters I end up with "?" instead of those characters.
Example:
Add a new search engine. Type the following as its name
"Tracking - Посылки"
The extension generates the search engine (it works), but its name changes to "Tracking - ???????"

**Comment by evilpie** [comment]
Thanks for the report. Apparently this is some kind of issue with paste.mozilla.org. When you go there and paste the XML file

```
<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
<ShortName>Tracking - Посылки</ShortName>
<InputEncoding>UTF-8</InputEncoding>
<Image height="16" width="16">https://github.com/favicon.ico</Image>
<Url type="text/html" method="GET" template="https://github.com/search?q={searchTerms}"/>
</OpenSearchDescription>
```
You will see the same incorrect ??? in the name

**Comment by Acid-Crash** [comment]
Hi,
Just updated to 3.1 and Cyrillic chars are working fine now.
Thank you!
