### ISSUE TITLE
Missing Page Action Button problem

### ISSUE THREAD

**Issue by orropid** [evilpie/add-custom-search-engine#25]
Hi,

As other users have already pointed out on the Mozilla review page, the  addon is not usable anymore. The process of adding a new search engine involves the dropdown menu in the address bar — something that is missing from the latest instances of Firefox. I tried to follow some online suggestions to get that feature back into Firefox, by tweaking some about:config lines, but to no effect. It's a shame, because now adding custom search engines is parctcally impossible. Can we hope for an update of the addon that brings back functionality?

Cheers,

Steve

**Comment by evilpie** [comment]
Not sure what you are talking about? The dropdown in the address bar is the "new way" of adding a search engine. It definitely still exists and works.

**Comment by orropid** [comment]
I am talking about this:

https://support.mozilla.org/en-US/questions/1279774
https://support.mozilla.org/en-US/questions/1289240
https://support.mozilla.org/en-US/questions/1290046
https://support.mozilla.org/en-US/questions/1284323

The missing drop-down, which the addon now requires.

**Comment by orropid** [comment]
At least two other users pointed out the issue in their reviews:
https://addons.mozilla.org/en-US/firefox/addon/add-custom-search-engine/reviews/?src=search

They were instructed to start a thread here. They haven't, so I did.

**Comment by evilpie** [comment]
Oh you are talking about that down arrow. You have to click the three dots ···. https://github.com/evilpie/add-custom-search-engine/blob/master/icons/urlbar.png There should be instructions pointing that. Are those missing for you?

**Comment by orropid** [comment]
Yes, the three dot thing is gone. That is the problem.

**Comment by evilpie** [comment]
That sounds like some kind of CSS modification or custom preferences gone wrong. Does it reproduce with a new profile?

**Comment by orropid** [comment]
This was it! A line in the CSS kept the page action button in the url bar hidden, even after the about:config tweaks:
#pageActionButton { display: none !important; }

Since other people also had this problem, maybe you should consider adding extra warning about it.
Thank you.
Steve
