### ISSUE TITLE
Can't add most search sites through the new "three dot" input format

### ISSUE THREAD

**Issue by d-a10** [evilpie/add-custom-search-engine#26]
Can you restore the manual filling in of the form so that a user can add a search engine manually and automatically through the new "3 dot" thing? Removing the option to manually input a search engine was a mistake as many search pages are not automatically registered by the new "3 dot" search bar.

**Comment by evilpie** [comment]
> Removing the option to manually input a search engine was a mistake

I am not quite sure what you mean. If you mean the prompt that we used to use, that feature has been disabled in Firefox since version 78, so we can't use.

**Comment by evilpie** [comment]
@d-a10 Can you please clarify your issue report? Otherwise I will close this.

**Comment by d-a10** [comment]
Hi,

I did look through the Mozilla's prs shortly after posting and found that this has been removed as functionality due to security concerns like you said. This can be closed.
