### ISSUE TITLE
Custom search engine is not available in FF Top Sites

### ISSUE THREAD

**Issue by rayx** [evilpie/add-custom-search-engine#28]
I added a custom search engine  using this add-on. It shows up properly in preference and search bar. My purpose is to add this search engine to FF Top Sites. But when I click the "Add Search Engine" menu located at its upper right corner, the custom search engine doesn't appear in the selection list. Any idea what's wrong?

This is with the latest version of FF (81.0) on ubuntu. Not sure if it's a bug with the add-on or FF Top Sites. Restarting FF doesn't help. Thanks for any suggestions.

**Comment by evilpie** [comment]
> the custom search engine doesn't appear in the selection list.

What does that mean exactly? Maybe you could provide some screenshots? The search bar on about:newtab uses your default search engine.

**Comment by rayx** [comment]
No, it's not about search bar on about:newtab page. It's about Top Sites.

Top Sites has support for adding search engine. See screenshot below (note the second item in the pop-up menu).

![screenshot-2020-10-01_10-31-59](https://user-images.githubusercontent.com/96338/94759504-b3d49100-03d2-11eb-8bcb-adf4ee18d798.png)

If you clicks on the "Add Search Engine" menu, it shows a pop-up window containing search engines for you to select.

![screenshot-2020-10-01_10-32-36](https://user-images.githubusercontent.com/96338/94759654-1037b080-03d3-11eb-87ea-8854e7939f9f.png)

The issue is the custom search engine added using the add-on is not among them.

**Comment by evilpie** [comment]
Ah thanks, I had never noticed this dialog before. I just tested this myself and it doesn't show up there for me either, even for search engines that show up in the search bar otherwise. I suggest you report a bug to Mozilla.
