### ISSUE TITLE
Suggestion: Use the website's favicon.ico by default

### ISSUE THREAD

**Issue by pizzahut2** [evilpie/add-custom-search-engine#3]
Hallo evilpie! Wenn man das Icon nicht angibt, wäre es m.M.n. sinnvoll, die favicon.ico-Datei der betreffenden Webseite zu verwenden, damit man weiß, um welche Suchmaschine es sich handelt. Klar kann ich das auch von Hand eingeben. Es sollte aber der Standard-Fall sein, wenn die Angabe nur optional ist.

**Comment by evilpie** [comment]
Thank you, this is a good idea.
