### ISSUE TITLE
Search through drag-and-drop onto a new tab stopped working for some engines

### ISSUE THREAD

**Issue by github-account1111** [evilpie/add-custom-search-engine#30]
Dragging highlighted text onto the space between tabs or the end of the tab bar used to open a new tab and search for it using the default search engine - in my case, Startpage. Since updating FF to 83, performing the aforementioned action has just been opening the Startpage homepage.

To see if this is an issue on Startpage's end I added Duckduckgo and assigned it default, and it exhibited the same issue.

Interestingly, this does not seem to happen with Qwant or Google.

Note: dragging highlighted text onto a tab works properly with all engines and performs a search for the text in that tab. Regular searching through the address bar also works.

**Comment by evilpie** [comment]
This sounds like a Firefox issue.

**Comment by github-account1111** [comment]
Does merely sounding like a Firefox issue warrant closing it? Have you at least tried reproducing?

If anything, the fact that only certain engines exhibit this behavior makes it sound like a non-FF issue to me.

**Comment by evilpie** [comment]
Can you search normally with these engines? i.e using the search bar or explicitly selecting them in the URL bar?
I can't reproduce this problem when installing the engine provided by startpage.com.

It's still extremely unlikely this is a problem with my extension and we can't workaround issues like this anyway.
