### ISSUE TITLE
Cannot add an engine: "Firefox could not install the search engine from: https://file.io/8FYC27VcLq9Q"

### ISSUE THREAD

**Issue by lepczynski** [evilpie/add-custom-search-engine#34]
Hi,
Firstly, thank you for creating this addon, it's a great thing!

I get this error,
`Firefox could not install the search engine from: https://file.io/8FYC27VcLq9Q`  
 while trying to add:
Name: `IMG`
SearchURL: `https://www.google.com/images?q=%s`  
  
![add search engine error 2021 04 26-12 13](https://user-images.githubusercontent.com/23107895/116074195-af830480-a691-11eb-8051-842eb9176950.png)

 
It would be awesome to be able to setup this engine.

**Comment by evilpie** [comment]
You are using an outdated version. I stopped using file.io since Jun 23, 2020 in Version 3.0.

**Comment by lepczynski** [comment]
Thank a lot for a quick reply! : )
I was not aware, that it was not upgraded, solved the problem, great !
