### ISSUE TITLE
ADD context menu option to compete with "Add Keyword for this Search..."

### ISSUE THREAD

**Issue by allanlaal** [evilpie/add-custom-search-engine#35]
currently the entire adding process is quite cumbersome

is it possible to add a right click context menu option for Search Forms to add it as a Search Engine?

**Comment by allanlaal** [comment]
possibly helpful: https://hg.mozilla.org/mozreview/gecko/rev/53dcec859629116373e3b734552f084a7e278ec2#index_header

**Comment by evilpie** [comment]
The right click option only adds a keyword search. We can add enterprise policies either.

**Comment by allanlaal** [comment]
closing since technically not possible atm

**Comment by allanlaal** [comment]
would it be possibly to just prefill this plugins Add page from based on the Form keyword field I choose?

**Comment by allanlaal** [comment]
maybe a workaround for #45 ? (if Page Context menu has full access to page)
