### ISSUE TITLE
Does this extension support the file:// protocol?

### ISSUE THREAD

**Issue by maxbla** [evilpie/add-custom-search-engine#36]
A programming language I'm using has [HTML API docs](https://doc.rust-lang.org/std/?search=%s) with a search feature. They're accessible over the internet using the https://, but I'd like to use them offline. I have them downloaded on my computer at `file:///home/redacted/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/std/index.html?search=%s`. I can add the online api docs search as a search engine, but when I try to add the offline version as a search engine, I get the error "Firefox could not download the search plugin from: https://paste.mozilla.org/HVcDZkD5/raw", despite the fact that the paste.mozilla.org link contains what looks like the right stuff. I suspect there is some permission issue with the file:// protocol.

<details>
  <summary>pastebin text</summary>
  
```xml
<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
<ShortName>test</ShortName>

<InputEncoding>UTF-8</InputEncoding>
<Image height="16" width="16">null/favicon.ico</Image>
<Url type="text/html" method="GET" template="file:///home/redacted/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/std/index.html?search={searchTerms}"/>

</OpenSearchDescription>
```
  
</details>

**Comment by evilpie** [comment]
Firefox doesn't support adding file:// URLs via OpenSearch: https://searchfox.org/mozilla-central/rev/7a2cf04303cf6d4b684905a1af936b6da5e7ef59/toolkit/components/search/SearchEngine.jsm#384

**Comment by maxbla** [comment]
Darn. Thanks for this add-on.
