### ISSUE TITLE
New tab for Google search

### ISSUE THREAD

**Issue by RaSTuS26** [evilpie/add-custom-search-engine#38]
I've successfully added google search for the default search engine on FF89, thanks for that.

Problem is the search opens in the currently active tab rather than opening a new tab, is there a way to fix this behaviour?

**Comment by evilpie** [comment]
This is not really something my extension can influence. I think you can configure Firefox to do this: https://support.mozilla.org/en-US/questions/1200719

**Comment by RaSTuS26** [comment]
Thanks so much @evilpie , works like a charm. I did a search before opening this issue but unfortunately that answer was missing.

I'll close the issue now.
