### ISSUE TITLE
No "Add [SearchEngineName]" when right clicking the address bar

### ISSUE THREAD

**Issue by lomirus** [evilpie/add-custom-search-engine#39]
[![RSY7an.png](https://z3.ax1x.com/2021/06/18/RSY7an.png)](https://imgtu.com/i/RSY7an)

my config:
|Key|Value|
|---|---|
|Name|Google|
|Search URL|https://www.google.com/search?client=firefox-b-d&q=%s&safesearch=off|
|Icon (Optional)|https://www.google.com/favicon.ico|

P.S. I've removed the default google search engine before adding this.

**Comment by evilpie** [comment]
Does it work with a name like "Google2" ?

**Comment by lomirus** [comment]
> Does it work with a name like "Google2" ?

Yes, now it works. But if I can just name it the "Google"? "Google2" sounds a little strange since I've removed the old "Google".

**Comment by evilpie** [comment]
I think completely removing some builtin search engines might not work. Sadly there is nothing we can do here.

**Comment by Gersonzao** [comment]
> I think completely removing some builtin search engines might not work. Sadly there is nothing we can do here.

Please name this as a known issue in the AMO page description, because I reviewed it 3 times because I didn't knew of this 😅

**Comment by codepincher** [comment]
I am still having this issue...I've found the `https://paste.mozilla.org` link but have no idea how to add it. Nor do I know how to add the functionality for the custom search back to firefox.
