### ISSUE TITLE
[Feature Request] Ability to export and import an xml

### ISSUE THREAD

**Issue by FatOrangutan** [evilpie/add-custom-search-engine#4]
I'm currently using the `OpenSearch XML Preview` feature and then manually copy pasting the content into an xml for future use[1]. Then, when I need to import it, I manually copy-paste the relevant data into the fields.

Having a dedicated export and import feature would make it a bit more convenient for me.

[1] This is usually when I need to only slightly tweak a particular engine, say, change some parameters around. As Firefox doesn't offer a way to modify an installed engine, I remove and then re-add the modified one.

**Comment by evilpie** [comment]
It's a good idea. The only wrinkle is that this extension doesn't necessarily support everything that can be defined in an OpenSearch XML file. (e.g. multiple icons)

**Comment by atomGit** [comment]
[mozlz4-edit](https://addons.mozilla.org/en-US/firefox/addon/mozlz4-edit/) might help you

**Comment by evilpie** [comment]
I have been thinking about this from time to time and I don't think this is going to happen. I don't want to support every single OpenSearch feature, but without it importing is sort of error prone.

**Comment by evilpie** [comment]
You can view the raw XML when activating the advanced options. Importing is out of scope for this extension.
