### ISSUE TITLE
Add-on doesn't seem to work on the current version.

### ISSUE THREAD

**Issue by ericrbg** [evilpie/add-custom-search-engine#41]
Currently on FF91, the addon tends to fail whenever you try to install anything, with "download error
Firefox could not download the search plugin from: " and then your `paste.mozilla.com` URL.

As usually helpful from Mozilla, there's no further information, and the [relevant source](https://github.com/mozilla/gecko-dev/blob/d36cf98aa85f24ceefd07521b3d16b9edd2abcb7/browser/components/search/SearchUIUtils.jsm) seems to suggest this is just a general catch-all for failures, so it's pretty much impossible to see what's really causing this.

I have a feeling the XML may be making firefox throw a hissy fit, though - I'm trying to use features like search suggestions, and searching on a `localhost` url.

**Comment by evilpie** [comment]
I couldn't reproduce this. Is it possible that there was a temporary server or connection issue?

**Comment by kekkc** [comment]
Got the same problem currently. It worked for 3 submits, then at the 4th I got the same error. If I open the paste.mozilla.com link manually it shows me that the snippet cannot be found.
