### ISSUE TITLE
no longer works in FF 95.0.2

### ISSUE THREAD

**Issue by ballerburg9005** [evilpie/add-custom-search-engine#42]
When I go to sites like bing.com or duckduckgo.com, I don't get the "Add XXXX" anymore when I right click the address bar. The same is true to this plugin, the "Add XXXX" is missing. 

However, when I go to this URL I still get it: https://addons.mozilla.org/en-US/firefox/addon/add-custom-search-engine/ . Also it works for Wikipedia and Stackoverflow.

I tried this with a fresh Firefox profile folder and user.

I suppose this is some new kind of nasty BS they added last week because they hate their users. Can you check this out, or give me some ideas?

This other plugin works and I could add any URL as search engine with it : https://addons.mozilla.org/en-US/firefox/addon/search-engines-helper/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by evilpie** [comment]
Still works for me. The most likely explanation for this is usually that you are trying to add a search engine with a name that is already in use.

**Comment by ballerburg9005** [comment]
Hm, ok sorry you are right. It seems that when you remove search engines in FF, it only hides them from the list with no way to restore them but to erase all your custom ones. This is why I couldn't add certain ones, including Duckduckgo with your plugin. It was because they were hidden in the list under that name and rendered inaccessible.
