### ISSUE TITLE
Custom search for geoportail.gouv.fr

### ISSUE THREAD

**Issue by mll0** [evilpie/add-custom-search-engine#43]
Hi,

I don't where to turn regarding my concern, so hopefully you could help me.

I'm trying to crate a custom search for https://www.geoportail.gouv.fr/carte
But their form is in no way a classic HTML form, so I don't know how to build it.

Does anyone here know how to build such a custom search?

**Comment by evilpie** [comment]
I looked at this a while back and it doesn't seem like there is an easy way of converting this into a search engine that works in Firefox.
