### ISSUE TITLE
Firefox could not download the search plugin from: https://paste.mozilla.org/pJ3A8P8M/raw

### ISSUE THREAD

**Issue by shimself** [evilpie/add-custom-search-engine#45]
Firefox could not download the search plugin from: https://paste.mozilla.org/pJ3A8P8M/raw

that's it.  win 10 64   latest FF.

**Comment by evilpie** [comment]
@shimself Is this a persistent error for you?

**Comment by allanlaal** [comment]
this occurs when rel=search is not present for that field (~ https://github.com/evilpie/add-custom-search-engine/wiki/Technical-Limitation)

could we bypass this with creating a XML file 'Save As' instead in these cases? .. and then instructing the user how to import that xml search engine manually

**Comment by evilpie** [comment]
> this occurs when rel=search is not present for that field (~ https://github.com/evilpie/add-custom-search-engine/wiki/Technical-Limitation)

I am not sure what this means. This error usually happens when there is some connection issue on the user side or sometimes the paste.mozilla.org server has issue.

> could we bypass this with creating a XML file 'Save As' instead in these cases? .. and then instructing the user how to import that xml search engine manually

There really is no convenient way to manually import the OpenSearch XML file for a user.

**Comment by evilpie** [comment]
Closing

**Comment by nicbou** [comment]
I have the same issue here. I just installed the plugin. The URL works (if I access it manually) until I try to add the new search engine (by right-clicking the omnibar). Then it returns a 404. Could the extension delete the paste too quickly?

**Comment by evilpie** [comment]
Please open a new issue not comment on existing ones. The link that we produce from paste.mozilla.org is only valid once. So visiting it manually before installing the search engine via the UI is going to always fail.
