### ISSUE TITLE
Add feature to extract config file as xml(or json or whatever), and to import said file

### ISSUE THREAD

**Issue by d-a10** [evilpie/add-custom-search-engine#46]
As a user I would like to be able to export my saved search engines in my browser for when I go to use another computer I can then import them.

Specifically the issue is that firefox sync does not save or preserve my search engines from this extension, so being able to manually copy and past the xml(or json or whatever file) would be great.

**Comment by evilpie** [comment]
I think [Search Engine Helper](https://addons.mozilla.org/en-US/firefox/addon/search-engines-helper) provides this feature. I won't be implementing this feature in this extension as it's meant for a very specific use case.
