### ISSUE TITLE
Any way to backup / sync custom search engines

### ISSUE THREAD

**Issue by James-Oakley** [evilpie/add-custom-search-engine#49]
Do the custom search engines created with this (excellent) add-on sync to other Firefox browser instances using Firefox Sync? Or, failing that, is there any way to back these up so that if I had to reinstall my computer I'd be able to recover the search engines I'd created.

It's no big problem if the answer to both is "no"; it would just help to know so that I can create a bookmark corresponding to each search engine I create, to give me a reference point to rebuild things.

**Comment by evilpie** [comment]
> Do the custom search engines created with this (excellent) add-on sync to other Firefox browser instances using Firefox Sync?

Firefox doesn't sync search engines at all, so there is nothing we can do.

> Or, failing that, is there any way to back these up so that if I had to reinstall my computer I'd be able to recover the search engines I'd created.

Backup or restore functionality is outside the scope of this extension. I suggest you take a look at https://addons.mozilla.org/en-US/firefox/addon/search-engines-helper/.

**Comment by James-Oakley** [comment]
Appreciate the quick and helpful response, Tom. 😃
