### ISSUE TITLE
save my custom search engines

### ISSUE THREAD

**Issue by Raafliflaf** [evilpie/add-custom-search-engine#50]
is there a way to save the custom search engines i made using your app in a file, so that i can just put them back when i install firefox on another computer ?

**Comment by pedropsi** [comment]
Another option would be to somehow integrate this extension with [Mycroft Project](https://mycroftproject.com/) which used to be the "official" database of custom search engines

**Comment by Gersonzao** [comment]
Would be **very** useful since Firefox Sync doesn't sync search engines at all and I have to write down and then copy and paste all search engine opitons

**Comment by globdug** [comment]
I backup the file "search.json.mozlz4" in the profile folder to backup my search engines.
You can use this extension if curious on how search engines are stored in that file: https://addons.mozilla.org/it/firefox/addon/mozlz4-edit/

**Comment by evilpie** [comment]
There is also the extension [Search Engines Helper](https://addons.mozilla.org/en-US/firefox/addon/search-engines-helper/) (I can't personally vouch for this, because I haven't look at the source in a while)

Adding export/import to this extension is out of scope.
