### ISSUE TITLE
Don't turn spaces into + signs

### ISSUE THREAD

**Issue by jdlongman** [evilpie/add-custom-search-engine#51]
There should be an option not to turn spaces into + signs. This is incorrect behavior for searching e.g. torrent sites. If it has to be url parameterized maybe turn it into %20 if need be.

**Comment by evilpie** [comment]
As far as I know, this is not an option we can offer. Firefox decides how to encode.

**Comment by kazerniel** [comment]
Is there any way around it? Metacritic search has broken recently because + signs just get cut out of the string by the site, so the searched term has no spaces, and of course returns no hits. (If I try the site's internal search, spaces remain spaces in the URL bar.)
