### ISSUE TITLE
Not working anymore (with Firefox Nightly from v112.0a1 on)

### ISSUE THREAD

**Issue by Cr4z33** [evilpie/add-custom-search-engine#52]
Your addon stopped working with both Firefox Nightly for Android and Windows (cannot say about other OSs).

Any chance you can release a fix? :)

**Comment by evilpie** [comment]
Still working fine for me on Linux. I am not testing Android. Can you describe what doesn't work? @Cr4z33

**Comment by evilpie** [comment]
Most likely you already had an existing search engine with that name.

**Comment by Cr4z33** [comment]
Hmm unless it was hidden there was no evidence in the settings.

At the end of the day I am using a FF Nightly build so that might be part of the "game" I guess hehe.
