### ISSUE TITLE
Added search engine broke Firefox

### ISSUE THREAD

**Issue by K2AAE** [evilpie/add-custom-search-engine#55]
I added tusk search engine but the parameters do not work but I can not 'Delete' the added search engine, the 'Delete' button is grayed out. Now I only have a broken Tusk search engine regardless of what I do.

**Comment by Rizaaal** [comment]
Exactly, there seems to be no way to remove and/or modify existing search engines. Which is very bad... I hope we'll get an answer on this

**Comment by evilpie** [comment]
After adding a search engine is done any problem is purely caused by Firefox.
