### ISSUE TITLE
Can't find a way to add an @ keyword

### ISSUE THREAD

**Issue by SilvioLevy** [evilpie/add-custom-search-engine#58]
First, thanks for this extension/add-on!

I'm using it on Firefox 117.0.1, and apparently you can no longer create a keyword by going to about:preferences#search and editing the line for the custom search engine (contrary to the page where you create the keyword, which says "Tip: A keyword can be added by going to about:preferences#search after adding the search engine and editing the Keyword column"

Can this be fixed?

Also, it would be great if we could edit the URL without having to delete the search engine entry and recreating it, which is the only way I see to do that now. 

Thanks,

SIlvio Levy

**Comment by evilpie** [comment]
> and apparently you can no longer create a keyword by going to about:preferences#search and editing the line for the custom search engine

Still works for me. Make sure you don't have any duplicate keywords. (Potentially also bookmark keywords, but I am not sure) This is however out of scope for this extension.

> Also, it would be great if we could edit the URL without having to delete the search engine entry and recreating it, which is the only way I see to do that now.

This is impossible for extensions.
