### ISSUE TITLE
Getting NetworkError when attempting to add search engine

### ISSUE THREAD

**Issue by Vasiimr** [evilpie/add-custom-search-engine#59]
I'm getting an error adding search engines, the screenshot is attached. Regardless of what website or options I check, I always get this error upon clicking 'Add custom search engine':

TypeError: NetworkError when attempting to fetch resource.

![image](https://github.com/evilpie/add-custom-search-engine/assets/26633131/6f123c53-a0ac-4bcf-9dc6-270d4ec058f4)

Firefox 119.0.1, Windows 10

**Comment by jrcastine** [comment]
paste.mozilla.org forwards to https://prod.pastebin.prod.webservices.mozgcp.net.  Could this be a change that's causing the issue?

**Comment by Vasiimr** [comment]
I think that's the case, I opened up console to take a look at the requests being sent out after clicking the add custom search engine button and I see a few errors, one of which is talking about 'The Same Origin Policy disallows reading the remote resource at https://prod.pastebin.prod.webservices.mozgcp.net/api/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 405.'

![image](https://github.com/evilpie/add-custom-search-engine/assets/26633131/b3b7d2b1-f128-413c-a598-6ef4cf3e11d7)

**Comment by evilpie** [comment]
Thanks for the report. The redirect is probably temporary so updating the extension is probably a waste of time.

Otherwise I would be open to alternative suggestions for hosting that are trustworthy.

**Comment by Vasiimr** [comment]
> **Temporary fix**
> 
>     1. Clone this repo.
> 
>     2. Replace `https://paste.mozilla.org/api/` on `https://prod.pastebin.prod.webservices.mozgcp.net/api/` in search.js file
> 
>     3. In Firefox open `about:debugging`
> 
>     4. Click the `This Firefox` option
> 
>     5. Click the `Load Temporary Add-on` button
> 
>     6. Choose the `manifest.json` file.

I believe in addition you also need to replace line 38 in the manifest.json to be `https://prod.pastebin.prod.webservices.mozgcp.net/api/` rather than `https://paste.mozilla.org/api/` for this temporary fix to work

**Comment by v-v-vishnevskiy** [comment]
@Vasiimr Yeah, forgot about this. Thank you!

**Comment by evilpie** [comment]
https://paste.mozilla.org/ is operating normally again.

**Comment by CBroz1** [comment]
If you're seeing this error still, it's likely because your extension is out of date. A recent update allows you to select the paste URL in a drop down. To update...

1. Go to `about:addons`
2. Click `Add custom search engine`
3. Click the gear icon - top right
4. Click `Check for Updates`
