### ISSUE TITLE
get Name and Icon from Search URL

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [evilpie/add-custom-search-engine#6]
addon should get Name and Icon from Search URL, like https://github.com/soufianesakhi/firefox-search-engines-helper does

**Comment by evilpie** [comment]
We already add the `favicon.ico` URL, this extension uses `https://www.google.com/s2/favicons?domain=`, which is a Google service so I won't use that.

They also out-fill the name based on just the URL. I don't think this very useful, people can just enter this themselves.
