### ISSUE TITLE
Firefox could not download the search plugin from: https://paste.mozilla.org/...

### ISSUE THREAD

**Issue by blueglyph** [evilpie/add-custom-search-engine#64]
I cannot add a custom engine. When I complete the last but one step, I get an error (_Firefox could not download the search plugin from: https://paste.mozilla.org/..._)

## Steps to reproduce

- installed the plugin
- launched it through the extension menu
- Name = `Google_en`
- Search URL = `google.co.uk/search?q=%s&{google:RLZ}{google:originalQueryForSuggestion}{google:assistedQueryStats}{google:searchFieldtrialParameter}{google:language}{google:prefetchSource}{google:searchClient}{google:sourceId}{google:contextualSearchVersion}ie={inputEncoding}`
- (no advanced option)
- typed ENTER in one of the fields (I don't see any button to proceed)

=> I got a page telling me "Almost done just two more steps" [sic]

- right-clicked on the address bar, as indicated
- selected Add "Google_en"

=> I got an error in a popup, saying

```Firefox could not download the search plugin from: https://paste.mozilla.org/DmDjpMMK/raw```

![image](https://github.com/evilpie/add-custom-search-engine/assets/31706195/db636d56-ecbf-412f-838a-7b2665fb0ab2)

## What I tried
- allowed it to run on sites with restriction

=> no change

- visited the paste website

=> I got the following page:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
<ShortName>Google&#95;en</ShortName>

<InputEncoding>UTF-8</InputEncoding>

<Url type="text/html" method="GET" template="google.co.uk/search?q={searchTerms}&amp;{google:RLZ}{google:originalQueryForSuggestion}{google:assistedQueryStats}{google:searchFieldtrialParameter}{google:language}{google:prefetchSource}{google:searchClient}{google:sourceId}{google:contextualSearchVersion}ie={inputEncoding}"/>

</OpenSearchDescription>
```

## Environment

Windows 10, 64-bit
Firefox version 127.0.1

**Comment by blueglyph** [comment]
After trying many things, it seems to work without an underscore or a space in the name...

**Comment by evilpie** [comment]
I've seen a lot of problems when using built-in engine names before, but it's still surprising that `Google_en` doesn't work.

**Comment by blueglyph** [comment]
> I've seen a lot of problems when using built-in engine names before, but it's still surprising that `Google_en` doesn't work.

My mistake: there were two changes. I've tried again, and `Google_en` is fine, but not prefixing the URL with `https://` isn't.

It's a very intuitive error message, though.
