### ISSUE TITLE
moz:SearchForm support?

### ISSUE THREAD

**Issue by rimas-kudelis** [evilpie/add-custom-search-engine#65]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/OpenSearch), Firefox supports a non-standard moz:SearchForm element in the OpenSearch XML. MDN doesn't document this element, but, according to [devdoc](https://devdoc.net/web/developer.mozilla.org/en-US/docs/Creating_OpenSearch_plugins_for_Firefox.html), it's supposed to provide "The URL to go to to open up the search page at the site for which the plugin is designed to search."

Have you considered adding support for this in your extension?

**Comment by evilpie** [comment]
As far as I know Firefox doesn't support this element anymore.

**Comment by rimas-kudelis** [comment]
I see. Well, that wouldn't be surprising, seeing how they decided to scale down their OpenSearch support five years ago.
