### ISSUE TITLE
[Feature Request] View Current search engines

### ISSUE THREAD

**Issue by Acid-Crash** [evilpie/add-custom-search-engine#8]
Sometimes it is needed to view already installed search engines.
Unfortunately, Firefox doesn't provide a simple way of doing this.
I was wondering whether it is possible to add such functionality via an extension.
At minimum, a simple tab that will show all currently saved search engines (its configs/patterns to be precise).

p.s. there are some extensions that do such thing but their UI is kinda rough/unpolished
https://addons.mozilla.org/en-US/firefox/addon/mozlz4-edit/

**Comment by evilpie** [comment]
I mean you can just go to `about:preferences#search` and scroll down. Are you looking for something else?

My philosophy for this add-on was to do one thing and do that well.

**Comment by Acid-Crash** [comment]
In about:preferences#search I can see only search engine name.
For example user has added a custom search engine via extension. 
Some time passes by and he would like to review the config of the  search engine he had added before: Search URL, Icon, Suggest URL. For example user would like to check if paths are up-to-date or simply wants to check predefined search engines configs.
We may predict that "Icon" isn't that important...
It is more less easy to identify "Search URL" (by simply initiating the search with empty query)
But it isn't that obvious how to identify "Suggest URL" in previously added search engine.

This situation was the main idea behind this feature request.
Also taking into account that extensions main purpose is to add engines, adding the possibility to view engines may increase its audience...

**Comment by atomGit** [comment]
i think the OP is looking for a search plugin editor, which i also think would be a great addition - a way to edit the json data for existing search plugins

to the OP: if the developer chooses to not add this functionality, you can use something like [mozlz4-edit](https://addons.mozilla.org/en-US/firefox/addon/mozlz4-edit/)

**Comment by evilpie** [comment]
Thanks @atomGit for your suggestion. This is out of scope for my extension.
