### ISSUE TITLE
use a more ethical paste service?

### ISSUE THREAD

**Issue by atomGit** [evilpie/add-custom-search-engine#9]
personally i don't like the "privacy" policy for file.io - please consider using a more ethical service

[PrivateBin](https://bin.snopyta.org/) ( [API](https://github.com/PrivateBin/PrivateBin/wiki/API] )

[Privnote - Send notes that will self-destruct after being read](https://privnote.com/)

**Comment by evilpie** [comment]
I looked into this a little bit and I can't figure out how to get an URL that will automatically delete, but also just returns the XML contents. It looks like this API always returns JSON with the data embedded in it.

**Comment by atomGit** [comment]
sorry, wasn't aware of the technicalities - i'm not a really a coder
